server:
  name: server
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
third_module:
  database:
    driver: mysql
    source: root:12345678@tcp(127.0.0.1:3306)/cat13?parseTime=True&loc=Local
    max_open_conns: 0
    max_idle_conns: 2
    conn_max_lifetime_seconds: 0
    conn_max_idle_time_seconds: 0
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    password: "facai888"
    db: 0
third_service: {}